kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: film-tracker
  template:
    metadata:
      labels:
        app: film-tracker
        role: backend
        type: api
    spec:
      containers:
        - name: film-tracker
          imagePullPolicy: Always
          image: gcr.io/film-tracker-318903/film-tracker:latest
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 30
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: film-tracker
    role: backend
    type: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
