apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: film-tracker
  template:
    metadata:
      labels:
        app: film-tracker
        role: backend
        type: database
    spec:
      containers:
        - name: postgresql
          image: postgres:9.6
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: film-tracker
    role: backend
    type: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
